<?php

namespace WabLab\Taxonomy\Test\Unit;

use PHPUnit\Framework\TestCase;
use WabLab\Taxonomy\Contract\Service\IAddTaxonomyService;
use WabLab\Taxonomy\Contract\Service\IService;
use WabLab\Taxonomy\Service\AbstractService;
use WabLab\Taxonomy\Service\AddTaxonomyService;

class AddTaxonomyServiceTest extends TestCase
{
    protected IService $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new AddTaxonomyService();
    }

    public function testCreatingAddNewServiceObject()
    {
        $this->assertInstanceOf(AddTaxonomyService::class, $this->service);
    }

    public function testThatAddNewServiceImplementsItsRelatedInterface()
    {
        $this->assertInstanceOf(IAddTaxonomyService::class, $this->service);
    }
    
    public function testThatProcessMethodReturnsClassReference() {
        $this->assertInstanceOf(AddTaxonomyService::class, $this->service->process());
    }
}